# LOGGING
logging:
  file: target/imobilus.log
  level:
    org.imobilus: DEBUG
    org.test.imobilus: DEBUG
    org.springframework: INFO
    org.hibernate: INFO

# DATABASE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/imobilus
    username: imobilus
    password: imobilus
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
