# LOGGING
logging:
  file: target/imobilius.log
  level:
    org.imobilus: DEBUG
    org.springframework: INFO
    org.hibernate: INFO

# DATABASE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/imobilius
    username: imobilius
    password: imobilius
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

# SECURITY
security:
  password:
    secret: secret

# LIQUIBASE
liquibase:
  enabled: true
  change-log: classpath:liquibase/config/master.xml
  url: jdbc:postgresql://localhost:5432/imobilius
  user: imobilius
  password: imobilius